---
title: 'Sturgeon Report Card: Angler Analytics'
author: "CDFW"
date: "October 5, 2015"
output: html_document
---

Began: 05-Oct-2015

This file creates a dataframe of all purchased sturgeon cards from desired years (e.g., 2013 to 2015). Anglers are classified as "avid" when an angler has purchased a sturgeon card in at least 2 consecutive years. Data are analyzed to show for which years anglers did not return to the Department his/her report card.

```{r Libraries and Source Files, echo=FALSE}

library(RODBC)
#library()

source_dir <- "C:/Data/jdubois/RSourcedCode/"

source(file = paste0(source_dir, "functions_data_import_export.R"))
source(file = paste0(source_dir, "functions_stucard_avidity.R"))

# clean up
rm(source_dir)

```

```{r Query List, echo=FALSE}

# create a list of sql queries; list must be named and dataframe(s) will be
# added to the global environment using that name
stu_angler_query_list <- list(
  PurchasedCards = ReadSqlFile(sql_file = "PurchasedReportCards.sql")#,
  #ParamQuery = ReadSqlFile(sql_file = "testParamQuery.sql", dir = "sql")
)



```



```{r Data Connection and Import, echo=FALSE}

# This section opens connection to SQL Server database that houses sturgeon 
# report card data from 2012 to present. The database is queried, and for each 
# query a dataframe is created in the global environment. The connection is 
# closed and dataframes are available for analyses.

QuerySqlServerDb(queries = stu_angler_query_list,
                 server_name = "74.120.125.240",
                 database = "CA", trusted = FALSE)



```


```{r Analytics, echo=FALSE}

AnglerAvidity <- GetAvidityData(card_data = PurchasedCards)

length(unique(AnglerAvidity$CustomerID)) - length(AnglerAvidity$CustomerID)

table(AnglerAvidity$IsAvid)

nrow(AnglerAvidity[AnglerAvidity$IsAvid == "yes" &
                     AnglerAvidity$nYearsNotRet > 0 &
                     AnglerAvidity$YearsNotRet != "2015", ])

```




End of report